export const ActionTypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCT",
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    ADD_TO_QTY: "ADD_TO_QTY",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    CHANGE_CART_QTY: "CHANGE_CART_QTY",
    SORT_BY_PRICE: "SORT_BY_PRICE",
    FILTER_BY_SEARCH: "FILTER_BY_SEARCH",
    CLEAR_FILTERS: "CLEAR_FILTERS",
    SORT_BY_CATEGORY: "SORT_BY_CATEGORY",
};